name: scheduled-index
on:
  schedule:
    - cron: '0 */6 * * *'   # every 6 hours (edit if needed)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install
        run: |
          cd crawler
          npm ci
      - name: Run indexer
        run: |
          cd crawler
          node generate_index.js
      - name: Commit generated index
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add site/index.json || true
          git commit -m "Update index" || echo "no changes to commit"
          git push
